[WEB-1] Add input and list components
HenrikHovhannisyan/To-do-list pull request #1
Opened 2021-12-02 05:14 UTC by HenrikHovhannisyan

2021-12-02 05:24 UTC, HenrikHovhannisyan commented on src/App.css
> +}
add new line

2021-12-02 05:24 UTC, HenrikHovhannisyan commented on src/App.js
>  function App() {
convert to arrow function

2021-12-02 05:24 UTC, HenrikHovhannisyan commented on src/components/to-do-list/inputs/Input.js
> +const list = []
move to component state

2021-12-02 05:24 UTC, HenrikHovhannisyan commented on src/components/to-do-list/inputs/Input.js
> +export default Input;
new line

2021-12-02 05:24 UTC, HenrikHovhannisyan commented on src/components/to-do-list/lists/List.js
> +export default List;
new line

2021-12-08 19:08 UTC, SaulReznik requested changes

2021-12-08 19:08 UTC, robhov97 commented on src/components/to-do-list/inputs/Input.js
> +                <List list={this.state.list} />
Move List to upper scope, leave Input component with only input

2021-12-08 19:08 UTC, robhov97 commented on src/components/to-do-list/inputs/Input.js
> +                <form onSubmit={this.inputSubmit}>
remove form tag

2021-12-08 19:08 UTC, robhov97 commented on src/components/to-do-list/inputs/Input.js
> +                    <input type="submit" value="Add" />
convert to button, set click handler here, instead of form submit
```suggestion
                    <button type="submit" value="Add" onClick={this.inputSubmit} />
```

2021-12-08 19:08 UTC, SaulReznik commented on src/components/to-do-list/inputs/Input.js
> +            list: [...prevState.list, this.state.value]
delete text inside of value here

2021-12-08 19:08 UTC, SaulReznik commented on src/components/to-do-list/lists/List.js
> +        <li key={e.toString()}>{e}</li>
```suggestion
        <li key={`${e.toString()}${index}}>{e}</li>
```

2021-12-08 19:08 UTC, SaulReznik commented on src/components/to-do-list/lists/List.js
> +    const list = props.list;
use object destructuring

2021-12-12 14:24 UTC, SaulReznik approved these changes

2021-12-12 14:24 UTC, merged